webtalk_init -webtalk_dir D:/flySimulator/flySimulator.sim/sim_1/behav/xsim/xsim.dir/flySimulator_bench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jun 29 15:12:28 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f93dcda6-0971-43f4-9c1f-088e07f0639e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0b78d9ce410c40c0a0cdcd1a7fab5931" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "182560 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "19" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "78.25_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "24400_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3568952228 -regid "" -xml D:/flySimulator/flySimulator.sim/sim_1/behav/xsim/xsim.dir/flySimulator_bench_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/flySimulator/flySimulator.sim/sim_1/behav/xsim/xsim.dir/flySimulator_bench_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/flySimulator/flySimulator.sim/sim_1/behav/xsim/xsim.dir/flySimulator_bench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
