# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/master.xdc

# IP: ip/xadc_wiz_0/xadc_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] -quiet

# IP: ip/rgb2dvi_0/rgb2dvi_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb2dvi_0 || ORIG_REF_NAME==rgb2dvi_0} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: d:/brembsFPGA/flySimulator.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc

# XDC: d:/brembsFPGA/flySimulator.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/brembsFPGA/flySimulator.gen/sources_1/ip/rgb2dvi_0/src/rgb2dvi.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rgb2dvi_0 || ORIG_REF_NAME==rgb2dvi_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/brembsFPGA/flySimulator.gen/sources_1/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc

# XDC: d:/brembsFPGA/flySimulator.gen/sources_1/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rgb2dvi_0 || ORIG_REF_NAME==rgb2dvi_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/brembsFPGA/flySimulator.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/brembsFPGA/flySimulator.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/brembsFPGA/flySimulator.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc

# XDC: d:/brembsFPGA/flySimulator.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
